### ISSUE TITLE
Could not get unknown property 'repo' on extension

### ISSUE THREAD

**Issue by srs** [ajoberstar/gradle-git-publish#25]
Hi.

I get this error when running Gradle 4. Have not tested Gradle 3.5 but I assume it works since I have seen a lot of examples using it. 

Looks like `gitPublishClose` sets a `repo` property on the extension. But the `repo` property does not exist. 

Here's the exception I get:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':gitPublishClose'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:242)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:235)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:224)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:121)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:102)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:96)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:612)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:567)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:96)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:745)
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'repo' for object of type org.ajoberstar.gradle.git.publish.GitPublishExtension.
        at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:86)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:61)
        at org.ajoberstar.gradle.git.publish.GitPublishExtension_Decorated.getProperty(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:50)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
        at org.ajoberstar.gradle.git.publish.GitPublishPlugin$_createCloseTask_closure6$_closure17.doCall(GitPublishPlugin.groovy:170)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:430)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:670)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:651)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 30 more
```

**Comment by fviolette** [comment]
I have the same issue in 3.5. In waiting for that fix, what Gradle/plugin combination could I use? I see the master branch is set to 3.4.

Thanks.

**Comment by ajoberstar** [comment]
Known tested versions are documented in the [release notes](https://github.com/ajoberstar/gradle-git-publish/releases) for each version of this plugin.

I'll have to add the latest Gradle versions into my compatibility suite to see when the issue arose.

**Comment by ajoberstar** [comment]
Using my compatibility suite, everything worked fine on 3.5, 3.5.1, 4.0, and 4.0.1. Can you provide a sample build that has this issue?

**Comment by stlhrt** [comment]
bug is reproducible in gradle 4.0.1, 3.5.1, 3.4.1
this is my test case: git@github.com:stlhrt/stlhrt.github.io.git

**Comment by ajoberstar** [comment]
This is strange. Using your test case it appears to fail in all cases (on the second and all further runs). Running `clean gitPublishPush` doesn't seem to fail. Also, I went all the way back to Gradle 3.0 and it still fails.

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':gitPublishReset'.
> Checkout returned unexpected result NO_CHANGE

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':gitPublishClose'.
> Could not get unknown property 'repo' for object of type org.ajoberstar.gradle.git.publish.GitPublishExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

BUILD FAILED in 2s
2 actionable tasks: 2 executed
```

Do you seen failures for both of these tasks?

**Comment by ajoberstar** [comment]
I think I see the issue in your test case. You specify a `repoUri` of `git@github.com:stlhrt/stlhrt.gihub.io.git` (note the missing **t** in `gihub.io.git`).

The plugin's issue is that it buries the exception that would tell you what's really going on. I would guess that's the bug that's affecting everyone in this thread. Once that's fixed you should see whatever true error you are encountering.

**Comment by ajoberstar** [comment]
Can you let me know if 0.2.2-rc.1 fixes the issue (i.e. reports a more helpful exception)?

**Comment by stlhrt** [comment]
The missing `t` fixed the issue but the plugin still isn't very helpful when errors occur.
For example, when target branch is missing then:

```
:gitPublishReset FAILED
:gitPublishClose FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':gitPublishReset'.
> Checkout returned unexpected result NO_CHANGE

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':gitPublishClose'.
> Could not get unknown property 'repo' for object of type org.ajoberstar.gradle.git.publish.GitPublishExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

BUILD FAILED
```

**Comment by ajoberstar** [comment]
@stlhrt Is that with 0.2.2-rc.1?

**Comment by stlhrt** [comment]
yes 0.2.2-rc.1 -
https://github.com/stlhrt/stlhrt.github.io/blob/develop/build.gradle

**Comment by ajoberstar** [comment]
0.2.2-rc.2 should remove the second exception. If you still get the first one after trying that, can you run with `--stacktrace` and post the full output? I was thinking that particular message was tied to the bug in 0.2.1, so not sure why it's still there.

**Comment by ajoberstar** [comment]
FYI, I did clone your project down and it seemed to do what I would expect (not the error you got). Here's what I did to test:

- `git clone git@github.com:stlhrt/stlhrt.github.io.git`
- `gradle wrapper --gradle-version=4.0.1`
- `./gradlew clean gitPublishPush --console=plain` (just to get more postable output)

This gives me:

```
:clean
:bake
Current implementation of storage does not support sbtree collections
Current implementation of storage does not support sbtree collections
:gitPublishReset
:gitPublishCopy
:gitPublishCommit
:gitPublishPush FAILED
:gitPublishClose

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gitPublishPush'.
> Problem pushing to remote.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 14s
7 actionable tasks: 7 executed
```
Running with stacktrace, shows "push not permitted", which makes sense since it's your repo.

**Comment by fviolette** [comment]
Been too busy to provide a sample but I confirm the fix does work now!

```
plugins {
    id 'com.github.eerohele.dita-ot-gradle' version '0.4.1'
    id 'org.ajoberstar.git-publish' version '0.2.2-rc.2'
}

defaultTasks 'gitPublishPush'

ditaOt.dir '../build/DITA-OT'

dita {
    input 'guidelines.ditamap'
    output 'out'
    transtype 'html5'
    properties {
      property name: 'generate.copy.outer', value: '3'
    } 
}

gitPublish {
    repoUri = '<repo>'
    branch = 'gh-pages'

    contents {
        from 'out'
    }
}

gitPublishPush.dependsOn clean, dita
```

**Comment by ajoberstar** [comment]
Thanks for the update! I'm cutting 0.2.2 right now. If anyone still has an issue, feel free to open/reopen to discuss further.
