### ISSUE TITLE
No such file or directory after upgrading to Gradle 4.2

### ISSUE THREAD

**Issue by sormuras** [ajoberstar/gradle-git-publish#35]
I think this exception is related to `gradle-git-publish` when running on Gradle 4.2 -- or am I mistaken?

```
Caused by: org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:253)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:85)
	at java_util_concurrent_Callable$call$0.call(Unknown Source)
	at org.ajoberstar.grgit.operation.AddOp.call(AddOp.groovy:53)
	at org.ajoberstar.grgit.operation.AddOp.call(AddOp.groovy)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at org.ajoberstar.grgit.internal.OpSyntax.mapOperation(OpSyntax.groovy:33)
	at org.ajoberstar.grgit.internal.OpSyntax$mapOperation.callStatic(Unknown Source)
	at org.ajoberstar.grgit.Grgit.add(Grgit.groovy)
	at org.ajoberstar.grgit.Grgit$add$7.call(Unknown Source)
	at org.ajoberstar.gradle.git.publish.GitPublishPlugin$_createCommitTask_closure5$_closure15.doCall(GitPublishPlugin.groovy:141)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:700)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:673)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 94 more
Caused by: java.io.IOException: No such file or directory
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.newTempFile(ObjectDirectoryInserter.java:273)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.toTemp(ObjectDirectoryInserter.java:200)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:144)

```

See log after the upgrade to Gradle 4.2 with complete stacktrace at https://junit.ci.cloudbees.com/blue/organizations/jenkins/JUnit5/detail/JUnit5/2230/pipeline

Or this is the latest one with more debug information:
https://junit.ci.cloudbees.com/blue/rest/organizations/jenkins/pipelines/JUnit5/runs/2260/log/?start=0

**Comment by ajoberstar** [comment]
Just checked my compatibility suite and it passes against 4.2. Not to say those are exhaustive, so could be missing something.

That exception though seems more tied to general JGit behavior. So it could be something just in the general config/environment of the grgit/jgit.

Did you make any other changes to your Gradle build when moving to 4.2?

**Comment by sormuras** [comment]
We did some changes like updating to latest versions of other plugins -- but after downgrading to Gradle 4.1 the gradle-git-publish, grgit/jgit issue disappeared.

**Comment by ajoberstar** [comment]
Interesting. I spent a few minutes trying to recreate this with the JUnit5 repo, but was having trouble (and the build is quite time consuming). If you can reproduce this in a smaller sample, that would be helpful.

**Comment by sormuras** [comment]
I was not able to create a smaller example that shows the issue. ):

We still do observe a working Gradle 4.1 + Jenkins setup. When we re-upgrade to Gradle 4.2.x (or later) and the issue raises again, I'll come back to you.

**Comment by ajoberstar** [comment]
Sounds good.

**Comment by danielvanmil** [comment]
Same issue here. Any progress on this? Thanks.

**Comment by ajoberstar** [comment]
No progress yet. If you have something reproducible that I can test with that would help.

**Comment by sormuras** [comment]
With JDK 9.0.1 released, we need to upgrade to Gradle 4.3 (`4.3-rc-2` at the moment) ... so chances are high that we'll run into this issue soon. Or there was a bug fix from 4.2 to 4.3... ;)

**Comment by sormuras** [comment]
The issue is still "alive".

See https://junit.ci.cloudbees.com/blue/organizations/jenkins/JUnit5/detail/master/23/pipeline/ for a `./gradlew --no-daemon --stacktrace --debug gitPublishPush` run.

**Comment by sormuras** [comment]
Mh...

Run **22** failed:
https://junit.ci.cloudbees.com/blue/organizations/jenkins/JUnit5/detail/master/22/pipeline/48/

Run **23** with `--stacktrace --debug` worked: https://junit.ci.cloudbees.com/blue/organizations/jenkins/JUnit5/detail/master/23/pipeline/48

Race condition?

**Comment by ajoberstar** [comment]
The stack trace [indicates](https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/internal/storage/file/ObjectDirectoryInserter.java#L273) we're failing creating a temp file inside of the object directory. Not sure why that would be missing at that point in the build. I'll try to run your project again tomorrow and see if I can reproduce it locally.

**Comment by sormuras** [comment]
Thanks in advance. I'll keep the `--debug` and `--stacktrace` options enabled -- if a publish action fails, the log should point us to the underlying issue. Hopefully.

Btw. I found following warning in the full log of run **23**:
```
05:48:01.808 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':gitPublishPush'
05:48:01.810 [WARN] [org.gradle.internal.featurelifecycle.LoggingDeprecatedFeatureHandler] The Task.dependsOnTaskDidWork() method has been deprecated and is scheduled to be removed in Gradle 5.0. Instead, check the value of "didWork()" for each task, or declare the task inputs and outputs and let Gradle decide what needs to be run.
	at org.gradle.api.internal.AbstractTask.dependsOnTaskDidWork(AbstractTask.java:580)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:158)
	at org.ajoberstar.gradle.git.publish.GitPublishPlugin$_createPushTask_closure6$_closure16.doCall(GitPublishPlugin.groovy:160)
```

**Comment by sormuras** [comment]
Run **24**  now failed with `--debug` and `--stacktrace` enabled:
https://junit.ci.cloudbees.com/blue/organizations/jenkins/JUnit5/detail/master/24/pipeline/

**Comment by ajoberstar** [comment]
So far I haven't gotten as far as your build does. On my desktop, it keeps crashing during the startup of gitPublishCopy trying to "delete stale outputs", which for some reason includes it trying to delete the repository. It specifically fails trying to delete one particular pack file.

Not entirely sure it's related, but if Gradle's trying to delete the repository (and succeeds), that could result in a lack of an object directory when it gets to the add in gitPublishCommit.

Will try backing this down to 4.1 and see if it still does the same for me.

**Comment by ajoberstar** [comment]
While that 4.1 runs, looking at Gradle source and it seems that [stale outputs cleanup](https://github.com/gradle/gradle/commit/dbf5680659900a5a0532ae2ae49677026390cf66#diff-158314ec83c2557de12be1a62bf562cb) was introduced in 4.2. This might be a matter of some missing output declarations on my part in the tasks in this plugin.

**Comment by ajoberstar** [comment]
And yes, 4.1 worked locally for me. Not sure why your build got farther than mine (maybe some Windows vs Linux differences), but seems like they both might be related to the stale outputs cleanup.

**Comment by ajoberstar** [comment]
Pushing out a 0.3.2-rc.1, including what seems to be a fix for this. Haven't figured out if/how I can make a test for this in this repo, but it seems to resolve the stale outputs issue in the junit5 project.

**Comment by sormuras** [comment]
I'll try it right away...

**Comment by sormuras** [comment]
Run **32** is green on the first attempt:
https://junit.ci.cloudbees.com/blue/organizations/jenkins/JUnit5/detail/master/32/pipeline

A comment from @wolfs or sombody else from Gradle would be welcome regarding this issue.

**Comment by sormuras** [comment]
Run [**33**](https://junit.ci.cloudbees.com/blue/organizations/jenkins/JUnit5/detail/master/33/pipeline) does not longer use `--debug` anymore. And it is green!

Thanks Andrew for fixing this!

**Comment by wolfs** [comment]
@sormuras I commented on #39. The problem you are experiencing is due to [better stale output file handling](https://docs.gradle.org/4.2.1/release-notes.html#safer-handling-of-stale-output-files) as already correctly analyzed by @ajoberstar. There are problems when tasks which declare outputs write to the same files/directories as tasks which do not. So either all the tasks writing to one directory should declare their input and outputs correctly or none of the tasks should declare any inputs or outputs.

**Comment by sormuras** [comment]
Thanks for chiming in @wolfs -- much appreciated.

**Comment by ajoberstar** [comment]
Thanks for testing @sormuras and thanks for the feedback @wolfs!

**Comment by ajoberstar** [comment]
@sormuras 0.3.2-rc.2 is out using a different approach mentioned by @wolfs. If you have a chance let me know if this one works for you too. It worked in my local copy of junit5.

**Comment by sormuras** [comment]
Upgraded to **0.3.2-rc.2** via https://github.com/junit-team/junit5/commit/460ac93958da3290f6a64775a92fee5eae9f9cf6 and it looks good to me: https://junit.ci.cloudbees.com/blue/organizations/jenkins/JUnit5/detail/master/35/pipeline

**Comment by ajoberstar** [comment]
Great! Thanks!

**Comment by chali** [comment]
Hi, see this issue back. I have the plugin in version `2.0.0` and Gradle `5.1.1`. I see this when `:gitPublishCopy` execution started.
`17:36:33.331 [INFO] [org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter] Deleting stale output file: /Users/mchalupa/projects/others/genie/build/gitPublish`

It happens only when I remove `.gradle` from the project. All following calls are working fine. However, our CI build always starts with fresh clone so it always fails.

**Comment by ajoberstar** [comment]
@chali Just from the description, I could see this as potentially expected (though undesired) behavior. With just the `.gradle/` deleted but `build/` still there, the cache and output dirs and out of sync. Deleting both `.gradle/` and `build/` (or neither) is probably what the Gradle folks would recommend.

If that doesn't work, can you open a new issue with some details of a working vs non-working config? Might be able to hunt down where the difference is.

**Comment by chali** [comment]
@ajoberstar thank you for quick follow up. The problem happens during a fresh clone and I verified that it happens even when I include `clean` task. I think that rules out the `.gradle/` and `build/` inconsistency as a cause. I will try to prepare a smaller example and open a new issue.
