### ISSUE TITLE
Algorithm negotiation fail

### ISSUE THREAD

**Issue by daggerok** [ajoberstar/gradle-git-publish#42]
Hello,

I've upgraded '0.3.0' -> '0.4.0-rc.2', and now always getting 'Algorithm negotiation fail' error on `gradle gitPublishPush` task

build.gradle

```groovy
plugins {
  id "base"
  id "org.asciidoctor.convert" version "1.5.3"
  id "org.ajoberstar.git-publish" version "0.4.0-rc.2"
  // // 0.3.0 version works fine
  // id "org.ajoberstar.git-publish" version "0.3.0"
}

asciidoctorj {
  version = "1.5.5"
}

asciidoctor {
  sourceDir = project.file("src")
  sources {
    include "index.adoc"
  }
  outputDir = project.file("$buildDir/asciidoc")
  attributes toc: "left",
      idprefix: "",
      docinfo1: "",
      icons: "font",
      idseparator: "-",
      setanchors: "true",
      "source-highlighter": "coderay",
      "toc-title": "Table of Contents",
      "build-gradle": file("build.gradle"),
      "endpoint-url": "https://daggerok.github.io/spring-data-examples"
}

gitPublish {
  repoUri = "git@github.com:daggerok/spring-data-examples.git"
  branch = "gh-pages"
  contents {
    from "$buildDir/asciidoc/html5"
    from "$projectDir/src/static"
    into "."
  }
}

asciidoctor.shouldRunAfter clean
build.dependsOn asciidoctor
gitPublishPush.dependsOn build
gitPublishPush.shouldRunAfter clean, build
task deploy(dependsOn: [gitPublishPush]) { shouldRunAfter build }
```

Note: adding to ~/.ssh/config doesn't helped:

```
KexAlgorithms diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha‌​1
```

As far as I can see, it's failing on `gitPublishReset` task

stacktrace

```bash
bash gradlew deploy -S

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':docs:gitPublishReset'.
> org.eclipse.jgit.api.errors.TransportException: git@github.com:daggerok/spring-data-examples.git: Algorithm negotiation fail

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':docs:gitPublishReset'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.gradle.internal.UncheckedException: org.eclipse.jgit.api.errors.TransportException: git@github.com:daggerok/spring-data-examples.git: Algorithm negotiation fail
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:63)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:151)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 31 more
Caused by: org.eclipse.jgit.api.errors.TransportException: git@github.com:daggerok/spring-data-examples.git: Algorithm negotiation fail
        at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:222)
        at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:160)
        at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:74)
        at java_util_concurrent_Callable$call$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at org.ajoberstar.gradle.git.publish.GitPublishPlugin$_createResetTask_closure3$_closure9.doCall(GitPublishPlugin.groovy:82)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:430)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:700)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:673)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        ... 37 more
Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:daggerok/spring-data-examples.git: Algorithm negotiation fail
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:163)
        at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:137)
        at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:274)
        at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:169)
        at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:199)
        ... 57 more
Caused by: com.jcraft.jsch.JSchException: Algorithm negotiation fail
        at com.jcraft.jsch.Session.receive_kexinit(Session.java:590)
        at com.jcraft.jsch.Session.connect(Session.java:320)
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:117)
        ... 61 more


* Get more help at https://help.gradle.org

BUILD FAILED in 5s
```

question: does anybody faced with such issue? 
It would be nice if you can help me fix it
Thanks!

---
Regards,
Maksim

**Comment by ajoberstar** [comment]
Quick note, 0.3.2 is the latest version. That 0.4.0-rc.2 was a mistaken release. It's likely close/identical to 0.3.2 though.

**Comment by ajoberstar** [comment]
This would be an issue with grgit (which handles the general Git layer) rather than this plugin. Could you recreate this [over there](https://github.com/ajoberstar/grgit/issues)?

**Comment by ajoberstar** [comment]
I'd also suggest providing a `--debug` log in case JGit or JSCH provide any more info about what's happening during this failed negotiation.

**Comment by daggerok** [comment]
Hello, @ajoberstar, and thanks for feedback

Maximum worked version for me is: 0.3.0

Here is --debug logs for [0.4.0-rc.2: 0.4.0-rc.2.log](https://github.com/ajoberstar/gradle-git-publish/files/1438997/0.4.0-rc.2.log)

I can provide logs for [0.3.2 as well: 0.3.2.log](https://github.com/ajoberstar/gradle-git-publish/files/1438994/0.3.2.log)


---
Regards,
Maksim

**Comment by daggerok** [comment]
Hello, @ajoberstar, thanks for feedback

yesterday latest maximum worked version for me was: 0.3.0

unfortunately today I updated brew, and now I see another errors... I don't know if this is a reason, I think it could be depends on git updated or something like that... 

gradle --debug for 0.3.0, [error: 1024 - 0.3.0.log](https://github.com/ajoberstar/gradle-git-publish/files/1439105/0.3.0.log)

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1024
        at com.jcraft.jsch.agentproxy.Buffer.getByte(Buffer.java:142)
        at com.jcraft.jsch.agentproxy.Buffer.getShort(Buffer.java:138)
        at com.jcraft.jsch.agentproxy.Buffer.getInt(Buffer.java:123)
        at com.jcraft.jsch.agentproxy.Buffer.getString(Buffer.java:181)
        at com.jcraft.jsch.agentproxy.AgentProxy.getIdentities(AgentProxy.java:112)
```

I can provide logs for 0.3.2 as well, [error: remote hung up unexpectedly - 0.3.2.log](https://github.com/ajoberstar/gradle-git-publish/files/1439109/0.3.2.log)

```
Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:daggerok/spring-data-examples.git: remote hung up unexpectedly
        at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:291)
        at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:169)
        at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:199)
        ... 58 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1024
```

and here is --debug logs for 0.4.0-rc.2, [same error - 0.4.0-rc.2.log](https://github.com/ajoberstar/gradle-git-publish/files/1439114/0.4.0-rc.2.log)

```
Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:daggerok/spring-data-examples.git: remote hung up unexpectedly
        at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:291)
        at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:169)
        at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:199)
        ... 58 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1024
```

anyway, right now even previously worked configuration is not worked anymore..

gradleVersion = "4.3"

note: I google little bit, and tried fix with `git config http.postBuffer 524288000`, but it's doesn't helped too

---
Regards,
Maksim

**Comment by ajoberstar** [comment]
Hi @daggerok, I moved this over to grgit, see the new linked issue.

**Comment by daggerok** [comment]
thank you, @ajoberstar
