### ISSUE TITLE
Exception in `gitPublishReset` Remote origin already exists.

### ISSUE THREAD

**Issue by ieugen** [ajoberstar/gradle-git-publish#87]
I'm trying to publish a static website and it fails with `Caused by: java.lang.IllegalStateException: Remote origin already exists.`

`./gradlew clean build --stacktrace`
```
 What went wrong:
Execution failed for task ':doc-sites:gitPublishReset'.
> Remote origin already exists.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':doc-sites:gitPublishReset'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:207)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:205)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:186)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:356)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.IllegalStateException: Remote origin already exists.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at org.ajoberstar.grgit.operation.RemoteAddOp.call(RemoteAddOp.groovy:63)
        at org.ajoberstar.grgit.operation.RemoteAddOp.call(RemoteAddOp.groovy)
        at java_util_concurrent_Callable$call.call(Unknown Source)
        at java_util_concurrent_Callable$call.call(Unknown Source)
        at org.ajoberstar.grgit.internal.OpSyntax.samOperation(OpSyntax.groovy:26)
        at org.ajoberstar.grgit.internal.OpSyntax$samOperation$1.callStatic(Unknown Source)
        at org.ajoberstar.grgit.service.RemoteService.add(RemoteService.groovy)
        at org.ajoberstar.gradle.git.publish.tasks.GitPublishReset.freshRepo(GitPublishReset.java:210)
        at org.ajoberstar.gradle.git.publish.tasks.GitPublishReset.lambda$reset$1(GitPublishReset.java:93)
        at org.ajoberstar.gradle.git.publish.tasks.GitPublishReset.reset(GitPublishReset.java:93)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

```

This is the repo:
https://github.com/ieugen/james-site/tree/JAMES-3226-site-build-publish

The configuration is 

```
plugins {
  id 'base'
  id 'com.github.node-gradle.node' version '2.2.4'
  id 'org.ajoberstar.grgit' version '4.0.2'
  id 'org.ajoberstar.git-publish' version '2.1.3'
}

node {
  // Version of node to use.
  version = '12.18.2'
  download = true
}

gitPublish {
    repoUri = 'https://github.com/apache/james-site.git'

    branch = 'asf-staging-test'
}

task generateDocs(type: NpxTask) {
  dependsOn npmInstall
  dependsOn gitPublishReset

  inputs.files('package.json', 'package-lock.json', 'antora-playbook.yml')
  inputs.dir(fileTree('node_modules').exclude('.cache'))
  outputs.dir(gitPublish.repoDir)

  command = 'antora'
  args = ['antora-playbook.yml']
}

tasks.build.dependsOn generateDocs
tasks.gitPublishCommit.dependsOn generateDocs
```

```
$ git --version 
git version 2.27.0

$ ./gradlew --version

------------------------------------------------------------
Gradle 6.5
------------------------------------------------------------

Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.7 (Oracle Corporation 11.0.7+10)
OS:           Linux 5.7.0-1-amd64 amd64

$ uname -a 
Linux daos-495 5.7.0-1-amd64 #1 SMP Debian 5.7.6-1 (2020-06-24) x86_64 GNU/Linux
```

**Comment by ieugen** [comment]
There is a git repo but no origin. 
```
$ cd doc-sites/build/gitPublish/
# gitPublish git:HEAD ○
$ git status 
On branch master

No commits yet

nothing to commit (create/copy files and use "git add" to track)
# gitPublish git:HEAD ○
$ git branch -a 
# gitPublish git:HEAD ○
$ git remote -v 
```

**Comment by ieugen** [comment]
I've added the --debug logs
```
[org.gradle.internal.execution.steps.CreateOutputsStep] Ensuring directory exists for property repoDirectory at /home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish
[org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':doc-sites:gitPublishReset'.
[org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Execute reset for :doc-sites:gitPublishReset' started
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.config/jgit/config.lock, cannot be racily clean
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.915639000, lastModified=1970-01-01 02:00:00.000000000, delta=1594105980915639000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.917435000, lastModified=2020-07-07 08:17:43.838576000, delta=6917078859000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.config/jgit/config.lock, cannot be racily clean
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.915639000, lastModified=1970-01-01 02:00:00.000000000, delta=1594105980915639000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.917435000, lastModified=2020-07-07 08:17:43.838576000, delta=6917078859000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/config, isRacyClean=false, read=2020-07-07 10:15:27.200954000, lastModified=1970-01-01 02:00:00.000000000, delta=1594106127200954000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/config, is unmodified
[org.gradle.api.Project] Failed to find existing Git publish repository. org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish
[org.gradle.internal.file.impl.DefaultDeleter] Deleting /home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.config/jgit/config.lock, cannot be racily clean
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.915639000, lastModified=1970-01-01 02:00:00.000000000, delta=1594105980915639000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.917435000, lastModified=2020-07-07 08:17:43.838576000, delta=6917078859000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.config/jgit/config.lock, cannot be racily clean
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.915639000, lastModified=1970-01-01 02:00:00.000000000, delta=1594105980915639000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.917435000, lastModified=2020-07-07 08:17:43.838576000, delta=6917078859000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config, isRacyClean=false, read=2020-07-07 10:15:27.212179000, lastModified=1970-01-01 02:00:00.000000000, delta=1594106127212179000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.config/jgit/config.lock, cannot be racily clean
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.915639000, lastModified=1970-01-01 02:00:00.000000000, delta=1594105980915639000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.917435000, lastModified=2020-07-07 08:17:43.838576000, delta=6917078859000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config, isRacyClean=false, read=2020-07-07 10:15:27.212179000, lastModified=1970-01-01 02:00:00.000000000, delta=1594106127212179000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.config/jgit/config.lock, cannot be racily clean
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.915639000, lastModified=1970-01-01 02:00:00.000000000, delta=1594105980915639000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.917435000, lastModified=2020-07-07 08:17:43.838576000, delta=6917078859000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config, isRacyClean=false, read=2020-07-07 10:15:27.212179000, lastModified=1970-01-01 02:00:00.000000000, delta=1594106127212179000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.config/jgit/config.lock, cannot be racily clean
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.915639000, lastModified=1970-01-01 02:00:00.000000000, delta=1594105980915639000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.917435000, lastModified=2020-07-07 08:17:43.838576000, delta=6917078859000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config, isRacyClean=false, read=2020-07-07 10:15:27.212179000, lastModified=1970-01-01 02:00:00.000000000, delta=1594106127212179000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.config/jgit/config.lock, cannot be racily clean
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.915639000, lastModified=1970-01-01 02:00:00.000000000, delta=1594105980915639000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.917435000, lastModified=2020-07-07 08:17:43.838576000, delta=6917078859000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config, isRacyClean=false, read=2020-07-07 10:15:27.212179000, lastModified=1970-01-01 02:00:00.000000000, delta=1594106127212179000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.config/jgit/config.lock, cannot be racily clean
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.915639000, lastModified=1970-01-01 02:00:00.000000000, delta=1594105980915639000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.917435000, lastModified=2020-07-07 08:17:43.838576000, delta=6917078859000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config, isRacyClean=false, read=2020-07-07 10:15:27.212179000, lastModified=1970-01-01 02:00:00.000000000, delta=1594106127212179000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.config/jgit/config.lock, cannot be racily clean
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.915639000, lastModified=1970-01-01 02:00:00.000000000, delta=1594105980915639000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.917435000, lastModified=2020-07-07 08:17:43.838576000, delta=6917078859000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config, isRacyClean=false, read=2020-07-07 10:15:27.212179000, lastModified=1970-01-01 02:00:00.000000000, delta=1594106127212179000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.config/jgit/config.lock, cannot be racily clean
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.915639000, lastModified=1970-01-01 02:00:00.000000000, delta=1594105980915639000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.917435000, lastModified=2020-07-07 08:17:43.838576000, delta=6917078859000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config, isRacyClean=false, read=2020-07-07 10:15:27.212179000, lastModified=1970-01-01 02:00:00.000000000, delta=1594106127212179000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.config/jgit/config.lock, cannot be racily clean
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.915639000, lastModified=1970-01-01 02:00:00.000000000, delta=1594105980915639000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.917435000, lastModified=2020-07-07 08:17:43.838576000, delta=6917078859000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config, isRacyClean=false, read=2020-07-07 10:15:27.212179000, lastModified=1970-01-01 02:00:00.000000000, delta=1594106127212179000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/HEAD.lock, create new FileSnapshot: lastRead=2020-07-07 10:15:27.231474000, lastModified=2020-07-07 10:15:27.228281000, size=23, fileKey=(dev=fe02,ino=937800)
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config.lock, create new FileSnapshot: lastRead=2020-07-07 10:15:27.232944000, lastModified=2020-07-07 10:15:27.228281000, size=78, fileKey=(dev=fe02,ino=972879)
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.config/jgit/config.lock, cannot be racily clean
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.915639000, lastModified=1970-01-01 02:00:00.000000000, delta=1594105980915639000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/etc/gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, isRacyClean=false, read=2020-07-07 10:13:00.917435000, lastModified=2020-07-07 08:17:43.838576000, delta=6917078859000 ns, racy<=2500000000 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/.gitconfig, is unmodified
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config.lock, isRacyClean=true, read=2020-07-07 10:15:27.232944000, lastModified=2020-07-07 10:15:27.228281000, delta=4663000 ns, racy<=18707500 ns
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config.lock, is racily clean
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config, create new FileSnapshot: lastRead=2020-07-07 10:15:27.234992000, lastModified=2020-07-07 10:15:27.228281000, size=78, fileKey=(dev=fe02,ino=972879)
[org.eclipse.jgit.internal.storage.file.FileSnapshot] file=/home/ieugen/proiecte/james/james-site/doc-sites/build/gitPublish/.git/config.lock, isRacyClean=true, read=2020-07-07 10:15:27.234992000, lastModified=2020-07-07 10:15:27.228281000, delta=6711000 ns, racy<=18707500 ns
[org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Execute reset for :doc-sites:gitPublishReset'
[org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Execute reset for :doc-sites:gitPublishReset' completed
[org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Snapshot outputs after executing task ':doc-sites:gitPublishReset'' started
[org.gradle.api.internal.tasks.execution.DefaultTaskSnapshotter] Snapshotting property repoDirectory (Output) for task ':doc-sites:gitPublishReset'
[org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Snapshot outputs after executing task ':doc-sites:gitPublishReset''
[org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Snapshot outputs after executing task ':doc-sites:gitPublishReset'' completed
[org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter] Removed task artifact state for task ':doc-sites:gitPublishReset' from context.
[org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Task :doc-sites:gitPublishReset'
[org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :doc-sites:gitPublishReset' completed
[org.gradle.execution.plan.DefaultPlanExecutor] :doc-sites:gitPublishReset (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.047 secs.
```

**Comment by ajoberstar** [comment]
As of 0.14.0 the reset task works differently, so I'm not sure if this would still happen. Feel free to reopen if it's still occurring.
