### ISSUE TITLE
No such file or directory after upgrading to 4.0.0

### ISSUE THREAD

**Issue by arhohuttunen** [ajoberstar/gradle-git-publish#99]
### Summary

When running the `gitPublishCommit` command with version 4.0.0 or above the build fails with `Exception caught during execution of add command.` caused by `No such file or directory`. This was working before in the 3.0.1 version.

### Build file

Example build file can be found in this project: https://github.com/arhohuttunen/awstestkit/blob/main/documentation/build.gradle.kts

There is currently no smaller project to demonstrate the issue but could be provided to reproduce the issue if needed.

### Output

```text
> Task :documentation:gitPublishCommit FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':documentation:gitPublishCommit'.
> Exception caught during execution of add command

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':documentation:gitPublishCommit'.
	stacktrace omitted
Caused by: org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:225)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:1)
	at java_util_concurrent_Callable$call$0.call(Unknown Source)
	at org.ajoberstar.grgit.operation.AddOp.call(AddOp.groovy:38)
	at org.ajoberstar.grgit.operation.AddOp.call(AddOp.groovy)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at org.ajoberstar.grgit.internal.OpSyntax.samOperation(OpSyntax.groovy:26)
	at org.ajoberstar.grgit.internal.OpSyntax$samOperation.callStatic(Unknown Source)
	at org.ajoberstar.grgit.internal.OpSyntax$samOperation.callStatic(Unknown Source)
	at org.ajoberstar.grgit.Grgit.add(Grgit.groovy)
	at org.ajoberstar.gradle.git.publish.tasks.GitPublishCommit.commit(GitPublishCommit.java:47)
	stacktrace omitted
Caused by: java.io.IOException: No such file or directory
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.newTempFile(ObjectDirectoryInserter.java:242)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.toTemp(ObjectDirectoryInserter.java:168)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:111)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:87)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:207)
	... 242 more
```

Looks similar to #65 and #35

**Comment by ajoberstar** [comment]
Sorry for the delay. I appreciate the sample project and the links to those related issues. It seems like if the `.gradle` directory isn't present, it does a "Clean stale outputs" in between each of the publish tasks. So it deletes the repo after copy runs and before commit starts.

Will look through Gradle's docs/code/issues to see how we're supposed to handle this. gradle/gradle#9041 is an indication of where they're headed (not allowing two tasks to use the same directory). And I get it, in general, but there are use cases like this that aren't feasible to handle if they're going to fiddle with the directories all the time. Needs to be some way to say "I've got this, just leave my files alone".

**Comment by ajoberstar** [comment]
I think I've got a solution, will be releasing it as 4.1.1.

**Comment by arhohuttunen** [comment]
Thanks for the fix!
